name: Upload

on:
  push:
    branches:
      - master
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: make files
        run: >
          node -v
          && mkdir dist/ && yarn && yarn mk-json

      - name: get yaml files
        run: cp -v *.yaml dist/

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.rsync_private_key}}
        with:
          flags: "-avzr --progress"
          options: ""
          ssh_options: ""
          src: "dist/*"
          dest: "rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}/"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
